# Generated by Django 4.1.2 on 2022-10-22 21:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('healers', 'Хилы'), ('dd', 'ДД'), ('merchants', 'Торговцы'), ('guildmasters', 'Гилдмастеры'), ('questgivers', 'Квестгиверы'), ('smiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('potionmasters', 'Зельевары'), ('spellmasters', 'Мастера заклинаний')], default='tanks', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('author', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
