# Generated by Django 4.1.2 on 2022-10-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
